### ISSUE TITLE
$respoinse.SetHeader fails

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShell/Polaris#84]
a call to  $response.SetHeader("test","test");  

Gives this error, no mater the header name or value

Invoke-WebRequest :
[0]:
System.Management.Automation.MethodInvocationException: Exception calling "SetHeader" with "2" argument(s): "Object
reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an
instance of an object.
   at PolarisCore.PolarisResponse.SetHeader(String headerName, String headerValue) in
C:\Polaris-master\PolarisCore\PolarisResponse.cs:line 23
   at CallSite.Target(Closure , CallSite , Object , String , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type
typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Object , String , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)At line:4
char:13
+             $response.SetHeader('test','test');
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ Invoke-WebRequest -UseBasicParsing -Uri http://localhost:8080/3?scrip ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by tylerl0706** [comment]
Thanks for tackling this!

**Comment by tylerl0706** [comment]
fixed in #85. Thanks again!
